bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_DKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_DKO_CP_1.tmp -o aln/Nkx2_5_DKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CM_2.tmp -o aln/Tbx5_WT_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CM_1.tmp -o aln/Nkx2_5_WT_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CM_1.tmp -o aln/Tbx5_WT_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CP_2.tmp -o aln/Tbx5_WT_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_Nkx2_5_WT_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_Nkx2_5_WT_CM_1.tmp -o aln/Tbx5_Nkx2_5_WT_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CM_1.tmp -o aln/Gata4_WT_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CP_1.tmp -o aln/Tbx5_WT_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CP_1.tmp -o aln/Nkx2_5_WT_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_NKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_NKO_CP_1.tmp -o aln/Nkx2_5_NKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CP_1.tmp -o aln/Gata4_NKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CP_1.tmp -o aln/Tbx5_NKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CP_1.tmp -o aln/Gata4_WT_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CM_3.tmp -o aln/Gata4_DKO_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_DKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_DKO_CM_1.tmp -o aln/Tbx5_DKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CP_1.tmp -o aln/Gata4_DKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CM_1.tmp -o aln/Gata4_NKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_DKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_DKO_CM_2.tmp -o aln/Tbx5_DKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CP_3.tmp -o aln/Gata4_NKO_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_DKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_DKO_CP_2.tmp -o aln/Tbx5_DKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_DKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_DKO_CP_1.tmp -o aln/Tbx5_DKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CM_2.tmp -o aln/Gata4_DKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CP_3.tmp -o aln/Tbx5_NKO_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CP_2.tmp -o aln/Gata4_DKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CP_3.tmp -o aln/Gata4_TKO_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CM_2.tmp -o aln/Gata4_TKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CP_2.tmp -o aln/Gata4_TKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CM_2.tmp -o aln/Gata4_WT_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CM_3.tmp -o aln/Gata4_TKO_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CM_1.tmp -o aln/Gata4_DKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CP_2.tmp -o aln/Tbx5_NKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CM_3.tmp -o aln/Tbx5_WT_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CM_2.tmp -o aln/Gata4_NKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CP_2.tmp -o aln/Gata4_WT_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_Nkx2_5_WT_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_Nkx2_5_WT_CM_3.tmp -o aln/Tbx5_Nkx2_5_WT_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CM_1.tmp -o aln/Tbx5_NKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CP_3.tmp -o aln/Nkx2_5_TKO_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CM_2.tmp -o aln/Nkx2_5_TKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_NKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_NKO_CM_1.tmp -o aln/Nkx2_5_NKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CP_2.tmp -o aln/Nkx2_5_TKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CM_3.tmp -o aln/Nkx2_5_TKO_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CM_2.tmp -o aln/Nkx2_5_WT_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CP_2.tmp -o aln/Gata4_NKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_NKO_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_NKO_CP_2.tmp -o aln/Nkx2_5_NKO_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CM_3.tmp -o aln/Gata4_WT_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_Nkx2_5_WT_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_Nkx2_5_WT_CM_2.tmp -o aln/Tbx5_Nkx2_5_WT_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CP_3.tmp -o aln/Nkx2_5_WT_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CM_3.tmp -o aln/Nkx2_5_WT_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_NKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_NKO_CM_2.tmp -o aln/Nkx2_5_NKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CM_1.tmp -o aln/Gata4_TKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CM_3.tmp -o aln/Tbx5_NKO_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_WT_CP_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_WT_CP_2.tmp -o aln/Nkx2_5_WT_CP_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_NKO_CM_2.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_NKO_CM_2.tmp -o aln/Tbx5_NKO_CM_2.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_NKO_CM_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_NKO_CM_3.tmp -o aln/Gata4_NKO_CM_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_WT_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_WT_CP_3.tmp -o aln/Gata4_WT_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_TKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_TKO_CP_1.tmp -o aln/Gata4_TKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CM_1.tmp -o aln/Nkx2_5_TKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_TKO_CP_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_TKO_CP_1.tmp -o aln/Nkx2_5_TKO_CP_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Nkx2_5_DKO_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Nkx2_5_DKO_CM_1.tmp -o aln/Nkx2_5_DKO_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_WT_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_WT_CP_3.tmp -o aln/Tbx5_WT_CP_3.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Tbx5_Nkx2_5_WT_CM_1.fastq.gz | samtools sort -@ 16 -O bam -T aln/Tbx5_Nkx2_5_WT_CM_1.tmp -o aln/Tbx5_Nkx2_5_WT_CM_1.bam
bwa mem -t 48 /data/data/genomes/mm10.fa fastq/Gata4_DKO_CP_3.fastq.gz | samtools sort -@ 16 -O bam -T aln/Gata4_DKO_CP_3.tmp -o aln/Gata4_DKO_CP_3.bam
